### ISSUE TITLE
mirror cam

### ISSUE THREAD

**Issue by dunland** [dunland/cspy#2]
mirrored cam doesn't work with realsense-cam:

``` python
Traceback (most recent call last):
  File "/home/dunland/github/cspy/run.py", line 95, in <module>
    cityscopy.scan()
  File "/home/dunland/github/cspy/cityscopy.py", line 163, in scan
    self.scanner_Traceback (most recent call last):
  File "/home/dunland/github/cspy/run.py", line 95, in <module>
    cityscopy.scan()
  File "/home/dunland/github/cspy/cityscopy.py", line 163, in scan
    self.scanner_function(self.multiprocess_shared_dict)
  File "/home/dunland/github/cspy/cityscopy.py", line 298, in scanner_function
    color_frame = cv2.flip(color_frame, 1)
TypeError: Expected Ptr<cv::UMat> for argument 'src'
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dunland/github/cspy/cityscopy.py", line 494, in create_data_json
    scan_results = multiprocess_shared_dict['scan']
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 834, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipefunction(self.multiprocess_shared_dict)
  File "/home/dunland/github/cspy/cityscopy.py", line 298, in scanner_function
    color_frame = cv2.flip(color_frame, 1)
TypeError: Expected Ptr<cv::UMat> for argument 'src'
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dunland/github/cspy/cityscopy.py", line 494, in create_data_json
    scan_results = multiprocess_shared_dict['scan']
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 834, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by dunland** [comment]
seems fixed
